const IOT_STATUS_CODE =
{
  OK: 0x01,
  DEVICE_NOT_FOUND: 0xA1,
  OPERATION_INVALID_PARAMS: 0x104
};

const CNC_STATUS =
{
  UNKNOWN: 0,
  DISCONNECTED: 1,
  IDLE: 2,
  RUNNING: 3,
  ERROR: 4
};

const CNC_STATUS_LABEL =
{
  [CNC_STATUS.UNKNOWN]: "UNKNOWN",
  [CNC_STATUS.DISCONNECTED]: "DISCONNECTED",
  [CNC_STATUS.IDLE]: "IDLE",
  [CNC_STATUS.RUNNING]: "RUNNING",
  [CNC_STATUS.ERROR]: "ERROR"
};

module.exports =
{
  IOT_STATUS_CODE,
  CNC_STATUS,
  CNC_STATUS_LABEL
};
